### ISSUE TITLE
Incompatible with vagrant 1.8+

### ISSUE THREAD

**Issue by regularfry** [sky-uk/vagrant-vrealize#1]
Trying to install this plugin into vagrant 1.8.1 gives this error:

```
The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "rest-client":
  In Gemfile:
    rest-client (< 2.0, >= 1.6.0) ruby

    vagrant-share (>= 0) ruby depends on
      rest-client (~> 1.6.0) ruby

    vagrant-vrealize (= 0.0.1) ruby depends on
      vmware-vra (>= 0) ruby depends on
        rest-client (~> 1.8) ruby
```

**Comment by regularfry** [comment]
The patch to remove the rest-client dependency from `vmware-vra` is https://github.com/chef-partners/vmware-vra-gem/pull/28

**Comment by skylikejam** [comment]
Current git version installs OK on 1.9.1 - OK to close this?

**Comment by codespelunker** [comment]
I'm using it with 1.9.0 with no problems.  Ok by me.

**Comment by codespelunker** [comment]
@skylikejam will you or someone else be able to create a new release with these changes?

**Comment by skylikejam** [comment]
@codespelunker The situation's become a bit complicated.

The vmware-vra gem that this plugin uses has been version bumped to 2.0.0, and that version only supports vra 7.X - the vmware-vra version is not defined in the current rubygems version of this gem, so if anyone pulls that in, they'll get the vra7-only 2.0.0 version now. I've locked the vmware-vra version to 1.7.0 in the deps so that we can use it with our current vra6 system, but pushing that out to rubygems would break anyone who's using vra7 with the current rubygems release.

We're upgrading our vra to 7 in the next few of months, at which point we'll be able to use the latest vmware-vra gem. Pushing that to rubygems would break vra6 users out in the real world, and that sucks but it's probably better than clobbering people using the latest version of vra. Probably.

Any suggestions on how to make this work for everyone gladly received. Might have to split the plugin into vagrant-vrealize and vagrant-vrealize6, but that'll still break for existing users on vra6.

:(

**Comment by codespelunker** [comment]
That would explain why my use case is working.  I forked the project and built it myself, and we're using vra 7.1.  Is there an easy way to detect and dynamically include the appropriate library, or is that just too much work?

**Comment by skylikejam** [comment]
Good to hear the plugin works with v7. 

As far as I'm aware you can't specify multiple versions of a gem in a spec. I can't see a way of handling this manually in a way that doesn't involve doing messy things with rvm or similar either.
